ollionorg/flow-core

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-icon/f-icon.scss, packages/flow-core/src/components/f-pictogram/f-pictogram.ts
- Changed Icon and Emoji size in `f-pictogram`
=> FLOW-436 Revisit icon, text and emoji size in f-pictogram

.storybook/storybook.css, packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/figma/sync-md-file.js, packages/flow-core/html.html-data.json, packages/flow-core/package.json, packages/flow-core/src/components/f-button/f-button.scss, packages/flow-core/src/components/f-button/f-button.ts, packages/flow-core/src/components/f-counter/f-counter.scss, packages/flow-core/src/components/f-counter/f-counter.ts, packages/flow-core/src/components/f-div/f-div.scss, packages/flow-core/src/components/f-div/f-div.ts, packages/flow-core/src/components/f-icon-button/f-icon-button.scss, packages/flow-core/src/components/f-icon-button/f-icon-button.ts, packages/flow-core/src/components/f-icon/f-icon.scss, packages/flow-core/src/components/f-icon/f-icon.ts, packages/flow-core/src/components/f-pictogram/f-pictogram.scss, packages/flow-core/src/components/f-pictogram/f-pictogram.ts, packages/flow-core/src/components/f-text/f-text.scss, packages/flow-core/src/components/f-text/f-text.ts, packages/flow-core/src/mixins/scss/_mixins.scss, stories/f-button.stories.mdx, stories/f-counter.stories.mdx, stories/f-div.stories.mdx, stories/f-icon-button.stories.mdx, stories/f-icon.stories.mdx, stories/f-pictogram.stories.mdx, stories/f-text.stories.mdx
- Inheritance Rules added in various components, where if state is equal to inherit, then the particular component will inherit color of its parent.
Following are the components:
- `f-div`
- `f-icon`
- `f-text`
- `f-pictogram`
- `f-button`
- `f-icon-button`
=> FLOW-455 Implementation of Inheritance rules for Flow

.github/workflows/release.yml, packages/custom-elements-manifest-to-types/package.json, packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-tag/f-tag.scss
- Publishing packages to github registry.
=> :art: FLOW-556 publishing to github registry

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/html.html-data.json, packages/flow-core/package.json, packages/flow-core/src/components/f-tag/f-tag.scss, packages/flow-core/src/components/f-tag/f-tag.ts, stories/f-tag.stories.mdx
Introduced clickable flag to `f-tag` component.
=> feat: Added clickable flag to f-tag

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/html.html-data.json, packages/flow-core/package.json, packages/flow-core/src/components/f-button/f-button.ts, packages/flow-core/src/components/f-icon-button/f-icon-button.ts, packages/flow-core/src/components/f-input/f-input.ts, packages/flow-core/src/components/f-popover/f-popover.scss, packages/flow-core/src/components/f-popover/f-popover.ts, packages/flow-core/src/components/f-select/f-select.test.ts, packages/flow-core/src/components/f-select/f-select.ts, packages/flow-core/src/components/f-tooltip/f-tooltip.scss, packages/flow-core/src/components/f-tooltip/f-tooltip.test.ts, packages/flow-core/src/components/f-tooltip/f-tooltip.ts, packages/flow-core/src/index.ts, packages/flow-core/src/mixins/components/f-root/f-root.scss, packages/flow-core/src/mixins/components/f-root/f-root.ts, stories/f-button.stories.mdx, stories/f-icon.stories.mdx, stories/f-tooltip.stories.mdx
- `f-tooltip` as a component added, which could be used easily in all components using `tooltip="string"` or could be used as component using `f-tooltip`.
=> FLOW-633 f-tooltip

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/html.html-data.json, packages/flow-core/package.json, packages/flow-core/src/components/f-div/f-div.scss, packages/flow-core/src/components/f-div/f-div.ts, stories/f-div.stories.mdx
- Added `overflow="visible"` in `f-div`.
=> FLOW-637 | overflow visible added to f-div

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/html.html-data.json, packages/flow-core/package.json, packages/flow-core/src/components/f-popover/f-popover.scss, packages/flow-core/src/components/f-popover/f-popover.ts, stories/f-popover.stories.mdx
=> Revert "FLOW-658 | f-popover addition of two more placements"

.storybook/main.js, .storybook/manager-head.html, .storybook/manager.js, package.json, packages/flow-core/custom-elements.json, packages/flow-core/src/components/f-carousel/f-carousel.ts, yarn.lock
=> FLOW-758 Google analytics in storybook

.github/workflows/release.yml, packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-select/f-select.ts, packages/flow-core/src/components/f-select/render.ts
- `f-select`: `add-option` event emission logic fixed.
=> FLOW-785 `f-select` : `add-option` event emission logic fixed.

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-popover/f-popover.ts, packages/flow-table/custom-elements.json, packages/flow-table/src/components/f-table-schema/__snapshots__/f-table-schema.test.snap.js, packages/flow-table/src/components/f-table-schema/f-table-schema.test.ts, stories/f-popover.stories.mdx
- `f-popover` : `close-on-escape` and `stretch-height` boolean flags props added.
=> FLOW-786 | f-popover improvements

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-div/f-div.scss, packages/flow-core/src/components/f-select/handlers.ts, packages/flow-core/src/mixins/components/f-root/f-root.ts, packages/flow-table/custom-elements.json, stories/f-select.stories.mdx
- `search-input` event emitted when user changes search value in `f-select`.
=> 108 feature request f select allow type events to be emitted from f select

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-select/f-select.scss, packages/flow-core/src/components/f-select/handlers.ts, packages/flow-table/custom-elements.json, stories/f-select.stories.mdx
- `f-select` loading icon alignment and loading behavior fix.
=> FLOW-866 f-select loader alignment and behavior fix

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-text/f-text.scss, packages/flow-table/custom-elements.json
- `f-text` : `:host` style is affecting in form-builder, hence applied to `f-text` selelector only.
=> FLOW-866 f-text host styles updated

packages/flow-core/custom-elements.json
=> FLOW-868 history restored

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-input/f-input.ts, stories/f-input.stories.mdx
- f-input of type number converts zero to blank string.
=> FLOW-911 f-input of type number converts zero to blank string

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-file-upload/f-file-upload.ts, packages/flow-core/src/components/f-search/f-search.ts, packages/flow-core/src/utils/index.ts, packages/flow-core/src/utils/mime-extension-map.ts, packages/flow-table/custom-elements.json
- `f-file-upload` : mapping `MIME Type` with its extensions, and displaying extension (.docx, .ppt) instead of whole `MIME Type` being displayed.
- `f-search`: `data-qa-element-id` added.
=> FLOW-922 | f-file-uplaod Mime Type fix

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-select/f-select.ts, packages/flow-core/src/components/f-select/render.ts
- `f-select` value type fixed.
- `f-select` value rendering fixed if user pass value as array for single selection.
=> FLOW-924 f-select value type fixed

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-suggest/f-suggest.ts
- `f-search` result reactivity issue
=> FLOW-925 f-search result reactivity issue

.github/workflows/release.yml, packages/custom-elements-manifest-to-types/CHANGELOG.md, packages/custom-elements-manifest-to-types/package.json, packages/flow-code-editor/CHANGELOG.md, packages/flow-code-editor/package.json, packages/flow-core-config/CHANGELOG.md, packages/flow-core-config/package.json, packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-lineage/CHANGELOG.md, packages/flow-lineage/package.json, packages/flow-log/CHANGELOG.md, packages/flow-log/package.json, packages/flow-md-editor/CHANGELOG.md, packages/flow-md-editor/package.json, packages/flow-table/CHANGELOG.md, packages/flow-table/package.json
- Slack notification changelog config updated in release.yml file.
=> FLOW-940 slack notification meta data updated

.github/workflows/release.yml, .storybook/main.ts, README.md, package.json, packages/flow-code-editor/CHANGELOG.md, packages/flow-code-editor/README.md, packages/flow-code-editor/package.json, packages/flow-core-config/CHANGELOG.md, packages/flow-core-config/package.json, packages/flow-core/CHANGELOG.md, packages/flow-core/README.md, packages/flow-core/package.json, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/README.md, packages/flow-form-builder/package.json, packages/flow-lineage/CHANGELOG.md, packages/flow-lineage/README.md, packages/flow-lineage/package.json, packages/flow-log/CHANGELOG.md, packages/flow-log/package.json, packages/flow-md-editor/CHANGELOG.md, packages/flow-md-editor/README.md, packages/flow-md-editor/package.json, packages/flow-table/CHANGELOG.md, packages/flow-table/README.md, packages/flow-table/package.json, stories/flow-form-builder/about.mdx, stories/flow-lineage/introduction/about.mdx
=> fix Fix storybook build by removing sideEffects

packages/custom-elements-manifest-to-types/package.json, packages/flow-code-editor/package.json, packages/flow-core-config/package.json, packages/flow-core/package.json, packages/flow-form-builder/README.md, packages/flow-form-builder/package.json, packages/flow-lineage/CHANGELOG.md, packages/flow-lineage/KNOWN_SOLUTIONS.md, packages/flow-lineage/README.md, packages/flow-lineage/package.json, packages/flow-log/package.json, packages/flow-md-editor/package.json, packages/flow-table/package.json, stories/flow-form-builder/about.mdx
=> fix Fix paths to git repo and add documentation

packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-form-builder/src/components/f-form-array/f-form-array.ts, packages/flow-form-builder/src/modules/validation/validator.ts, packages/flow-form-builder/src/types.ts, stories/flow-form-builder/dynamic-validation-message.stories.ts, stories/flow-form-builder/f-formbuilder-field.ts
@cldcvr/flow-form-builder
- v1.8.0 and v1.8.1 commits merged.
=> FLOW-945 v1.8.0 and v1.8.1 commits merged.

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-tag/f-tag-global.scss, packages/flow-core/src/components/f-tag/f-tag.scss, stories/flow-core/f-tag.stories.js
- `f-tag`: width inherting issue fixed.
=> issue-156 f-tag width inheritance fixed

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-pictogram/f-pictogram.ts
=> FLOW-948 |  f-pictogram auto-bg bug

packages/custom-elements-manifest-to-types/CHANGELOG.md, packages/custom-elements-manifest-to-types/index.ts, packages/custom-elements-manifest-to-types/package.json, packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json
- Duplicate type import fixed.
---
- Duplicate type import fixed
---
- Duplicate type import fixed
=> Issue-170 : Duplicate type import fixed

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.test.ts, packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.ts, packages/flow-core/src/components/f-input/f-input.ts, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-form-builder/src/components/f-form-builder/f-form-builder.ts
- `f-date-time-picker` : clear icon taking 2 clicks to clear date value.
- `console.log` removed
=> issue-178 f-date-time-picker clear icon behaviour fixed

packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table/f-table.ts
- Vue : `f-table` gridTemplate creation fixed
-
=> FLOW-957 f-table grid template creation bug fixed for vue 3

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-popover/f-popover.ts, packages/flow-core/src/components/f-search/f-search.ts, stories/flow-core/f-search.stories.ts
- `f-popover` : reset `max-height` issue fixed.
=> FLOW-962 f-popover max-height issue fixed + f-search stories updated

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.ts
- `f-date-time-picker` : date parsing error message logic updated.
=> FLOW-964-2 FLOW-964 date parsing error mesasge logic updated

package.json, packages/flow-code-editor/CHANGELOG.md, packages/flow-code-editor/package.json, packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-lineage/CHANGELOG.md, packages/flow-lineage/package.json, packages/flow-log/CHANGELOG.md, packages/flow-log/package.json, packages/flow-md-editor/CHANGELOG.md, packages/flow-md-editor/package.json, packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, pnpm-lock.yaml, stories/flow-form-builder/login-form.stories.ts
- `lit` upgraded to v3.
<hr/>
- `lit` upgraded to v3.
<hr/>
- `lit` upgraded to v3.
<hr/>
- `lit` upgraded to v3.
<hr/>
- `lit` upgraded to v3.
<hr/>
- `lit` upgraded to v3.
<hr/>
- `lit` upgraded to v3.
=> FLOW-956 all packages upgraded to lit v3

packages/flow-core/README.md, packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table-schema/f-table-schema.ts, packages/flow-table/src/components/f-table/f-table-global.scss, packages/flow-table/src/components/f-tcell/f-tcell.scss, packages/flow-table/src/components/f-tcell/f-tcell.ts, stories/flow-table/f-tcell.stories.ts, stories/utils/mock-users-data.ts
- `align` property introduced on `f-tcell`.
=> FLOW-968  `align` property introduced on `f-tcell`.

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-color-picker/f-color-picker-global.scss, packages/flow-core/src/components/f-color-picker/f-color-picker.scss, packages/flow-core/src/components/f-color-picker/f-color-picker.test.ts, packages/flow-core/src/components/f-color-picker/f-color-picker.ts, packages/flow-core/src/components/f-div/f-div.ts, packages/flow-core/src/components/f-form-field/f-form-field.ts, packages/flow-core/src/index.ts, packages/flow-core/vite.config.ts, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-form-builder/src/components/f-form-builder/fields/color.ts, packages/flow-form-builder/src/components/f-form-builder/fields/index.ts, packages/flow-form-builder/src/modules/helpers.ts, packages/flow-form-builder/src/types.ts, pnpm-lock.yaml, stories/flow-core/f-color-picker.stories.ts, stories/flow-form-builder/f-formbuilder-field.ts
- `f-color-picker` element added.
- `f-color-picker` field integrated
=> FLOW-970 f-color-picker component

packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table-schema/f-table-schema.ts, packages/flow-table/src/components/f-tcell/f-tcell.ts, stories/flow-table/f-table-schema.stories.ts
- `f-table-schema` : header checkbox not updating state when rows selection updated.
- `@row-click` emitted when checkbox clicked.
=> FLOW-1029 header checkbox not updating in f-table-schema

packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table/f-table.ts, packages/flow-table/src/components/f-trow/f-trow.ts
- `:scope > ` querySelector not working in some browser
=> FLOW-1030 scope query selector fix

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-button/f-button.scss, packages/flow-core/src/components/f-button/f-button.ts, stories/flow-core/f-button.stories.js
- `f-button` `packed` category addition
=> FLOW-1036 | f-button packed category addition

docs/how-to-apply-ollion-theme.md, packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/mixins/scss/_text-tokens.scss
- `f-ollion-*` theme font tokens updated.
- Check `docs` directory for how to apply ollion theme.
=> FLOW-1042 ollion theme tokens updated

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-button/f-button.ts, stories/flow-core/f-text.stories.ts
- `f-button` : `icon-left` and `icon-right` sizes updated.
=> FLOW-1143 f-button : icon-left and icon-right sizes updated

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-icon-button/f-icon-button.scss, packages/flow-core/src/components/f-icon-button/f-icon-button.ts, stories/flow-core/f-icon-button.mdx, stories/flow-core/f-icon-button.stories.ts, stories/flow-form-builder/select-field-search-performance.stories.ts
- Implemented the `effect` attribute within the `f-icon-button` component to enhance user engagement and draw attention effectively.
=> FLOW-1222 effect attribute added to f-icon-button

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-progress-bar/f-progress-bar-global.scss, packages/flow-core/src/components/f-progress-bar/f-progress-bar.scss, packages/flow-core/src/components/f-progress-bar/f-progress-bar.ts, packages/flow-log/CHANGELOG.md, packages/flow-log/package.json, packages/flow-log/src/components/f-log/f-log-search-and-filters.ts, packages/flow-log/src/components/f-log/f-log.ts, stories/flow-core/f-progress-bar.mdx, stories/flow-core/f-progress-bar.stories.ts, stories/flow-log/f-log.stories.ts
- `circle` variant added in `f-progress-bar` to show progress in circle.
- `search-keyword` added to `f-log` element, to control search externally.
=> FDS-642 circle variant added in f-progress-bar

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-select/f-select.scss, packages/flow-core/src/components/f-select/f-select.test.ts, packages/flow-core/src/components/f-select/f-select.ts, packages/flow-core/src/components/f-select/render.ts, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-form-builder/src/components/f-form-builder/fields/select.ts, packages/flow-form-builder/src/types.ts, packages/flow-log/CHANGELOG.md, packages/flow-log/package.json, packages/flow-log/src/components/f-log/f-log.ts, pnpm-lock.yaml, stories/flow-core/f-select.mdx, stories/flow-core/f-select.stories.ts, stories/flow-form-builder/f-formbuilder-field.ts, stories/flow-form-builder/select-field-search-performance.stories.ts, stories/flow-lineage/f-lineage.stories.ts
- `f-select`: A virtualizer is utilized to render options, thereby enhancing rendering performance, particularly in scenarios where there are over 3K+ options available.
- `f-select` : `max-options-width` support added to customize options width.
- We previously rendered `f-select` options in the DOM regardless of its visibility. Starting from this release, options will only appear when `f-select` is open. Please update test cases accordingly.
- Scrollbar visibility enabled in F-log element.
- `maxOptionsWidth` property added to `select` field.
=> FDS-643 f-select options rendering logic updated

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-progress-bar/_f-progress-bar-variables.scss, packages/flow-core/src/components/f-progress-bar/f-progress-bar-global.scss, packages/flow-core/src/components/f-progress-bar/f-progress-bar.scss, packages/flow-core/src/components/f-progress-bar/f-progress-bar.ts, stories/flow-core/f-progress-bar.stories.ts
- Updated `f-progress-bar` dimensions of the circle variant.
=> FDS-645 Updated  dimensions of circle variant.

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-suggest/display-options.ts, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-form-builder/src/components/f-form-builder/fields/suggest.ts, packages/flow-form-builder/src/types.ts, stories/flow-form-builder/f-formbuilder-field.ts
- The issue with highlighting suggestions in `f-suggest` has been resolved.
- `suggestWhen` property support added to `suggest` field.
=> FDS-646 The issue with highlighting suggestions in  has been resolved.

packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table-schema/f-table-schema.ts, packages/flow-table/src/components/f-table/f-table.ts, stories/flow-table/f-table-schema.stories.ts, stories/flow-table/f-table.mdx, stories/flow-table/f-table.stories.ts
- `f-table` & `f-table-schema` : `highlight-column-hover` property added to control column header hover behavior.
=> FDS-650 `f-table` & `f-table-schema` : `highlight-column-hover` property added to control column header hover behavior.

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-checkbox/f-checkbox.scss, packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-tcell/f-tcell.scss
- `f-checkbox` label line-height fixed.
- `f-tcell` aligment in `f-table-schema` fixed.
=> FDS-657 f-checkbox line-height fixed

packages/flow-log/CHANGELOG.md, packages/flow-log/package.json, packages/flow-log/src/components/f-log/f-log.ts
- Scroll to searchKeyword when available.
=> FDS-657 f-log scroll to searchkeyword fixed

packages/flow-log/CHANGELOG.md, packages/flow-log/package.json, packages/flow-log/src/components/f-log/f-log-search-and-filters.ts, packages/flow-log/src/components/f-log/f-log.ts
- Not clearing highlight of last search
=> FDS-657 f-log Not clearing highlight of last search

packages/flow-core/CHANGELOG.md, packages/flow-core/figma/sync-colors.js, packages/flow-core/package.json, packages/flow-core/src/mixins/scss/_color-tokens.scss, packages/flow-core/src/mixins/scss/_text-tokens.scss
=> FDS-662 text tokens updated

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-file-upload/f-file-upload.ts
- File extension validation logic added when the user drops files
=> FLOW-1607 file extention validation logic added

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-select/f-select.ts, packages/flow-lineage/CHANGELOG.md, packages/flow-lineage/package.json, packages/flow-lineage/src/components/f-lineage/create/create-links.ts, packages/flow-lineage/src/components/f-lineage/draw/draw-links.ts, packages/flow-lineage/src/components/f-lineage/f-lineage.scss, packages/flow-lineage/src/components/f-lineage/f-lineage.ts, packages/flow-lineage/src/components/f-lineage/highlight/highlight-path.ts, packages/flow-lineage/src/components/f-lineage/lineage-types.ts, stories/flow-lineage/f-lineage.stories.ts
- `fClick` callback added in the link.
- `label` property added to display a label on the link.
- `showLabelOn` property added to customize label displaying behaviour either on click or hover;
- The `tooltip` property was added to display more information about the link
- `f-select` : call `updateDimentions` only while opening.
=> FDS-664 fClick added on link

packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table-schema/f-table-schema-global.scss, packages/flow-table/src/components/f-table-schema/f-table-schema.scss, packages/flow-table/src/components/f-table-schema/f-table-schema.ts, stories/flow-table/f-table-schema.stories.ts
- `f-table-schema` infinie scroll issue fixed.
=> FDS-667 infinite scroll bug fixed
