ollionorg/flow-core

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/html.html-data.json, packages/flow-core/package.json, packages/flow-core/src/components/f-popover/f-popover.scss, packages/flow-core/src/components/f-popover/f-popover.ts, stories/f-popover.stories.mdx, yarn.lock
- `f-popover` two more placements added `left-fixed` and `right-fixed` to fix positions according to parent element towards left and right respectively.
=> FLOW-658 | f-popover addition of two more placements

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-emoji-picker/f-emoji-picker.ts, packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-tcell/f-tcell.ts, stories/f-table-schema.stories.mdx, stories/utils/mock-users-data.ts
`@cldcvr/flow-table`
- `f-tcell` : In actions callback, passing additional parameter as element for further implementation (like opening popover).
---
`@cldcvr/flow-core`
- `data-qa-remove-emoji` attribute added in `f-emoji-picker` for automation.
=> FLOW-845 FLOW-848 f-tcell actions callback updated

packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/html.html-data.json, packages/flow-core/package.json, packages/flow-core/src/components/f-pictogram/f-pictogram.scss, packages/flow-core/src/components/f-pictogram/f-pictogram.test.ts, packages/flow-core/src/components/f-pictogram/f-pictogram.ts, packages/flow-table/custom-elements.json, stories/f-pictogram.stories.mdx
- f-pictogram have an auto-bg flag where it auto assigns a color based on characters.
=> FLOW-836 | f-pictogram should have an auto-bg flag where it auto assigns a color based on characters #97

packages/flow-code-editor/custom-elements.json, packages/flow-core/CHANGELOG.md, packages/flow-core/custom-elements.json, packages/flow-core/package.json, packages/flow-core/src/components/f-popover/f-popover.scss, packages/flow-core/src/components/f-popover/f-popover.ts, packages/flow-core/src/mixins/components/f-root/f-root.scss, packages/flow-table/custom-elements.json, stories/f-popover.stories.mdx
- `f-popover`: for `overlay=false` aned `shadow=true` box-shadow appers in f-popover.
=> FLOW-928 | box-shadow for f-popover

packages/flow-code-editor/CHANGELOG.md, packages/flow-core-config/CHANGELOG.md, packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-pictogram/f-pictogram.scss, packages/flow-core/src/components/f-pictogram/f-pictogram.ts, packages/flow-form-builder/CHANGELOG.md, packages/flow-lineage/CHANGELOG.md, packages/flow-log/CHANGELOG.md, packages/flow-md-editor/CHANGELOG.md, packages/flow-table/CHANGELOG.md, stories/flow-core/f-pictogram.mdx, stories/flow-core/f-pictogram.stories.js, stories/flow-core/f-pictogram.stories.ts
- `f-pictogram`: added `category` prop having two types `fill` and `outline`.
=> FLOW-939 | f-pictogram adding category prop

packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-tcell/f-tcell.ts
- `disabled` added for f-table-cell actions.
=> Issue-157 | FLOW-946 | Disabling option in actions FTcellActions array in every row of f-table-schema

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.scss, packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.test.ts, packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.ts, stories/flow-core/f-breadcrumb.mdx, stories/flow-core/f-breadcrumb.stories.js, stories/flow-core/f-breadcrumb.stories.ts
- `f-breadcrumb`: added `variant` property which includes `text` and `icon` to display breadcrumbs in two different variants.
=> feat(ui): FLOW-941 | f-breadcrumbs variant prop introduced

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/mixins/components/f-root/f-root.ts, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-form-builder/src/modules/validation/default-validation-messages/index.ts, packages/flow-form-builder/src/types.ts, stories/flow-core/f-tooltip.stories.ts, stories/flow-form-builder/f-formbuilder-field.ts
- `tooltip` property now accepts object
```
{
text: string;
closable?: boolean;
placement?: FTooltipPlacement;
}
```
---
- `iconTooltip` type changed.
- `min-value` and `max-value` default messages updated.
=> issue-170 tooltip type updated to accept as object

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-div/f-div-global.scss
- `f-accordion`: max-width bug fixed for `f-aacordion` when direction="row"
=> FLOW-949 | f-accordion: width out of the bounds wrt parent div in a specific case

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/mixins/components/f-root/f-root.ts
- `f-tooltip` : `closable="true"` not working
=> issue-180 f-tooltip closable attribute not working fixed

packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table-schema/f-table-schema.test.ts, packages/flow-table/src/components/f-table-schema/f-table-schema.ts, stories/flow-table/f-table-schema.stories.ts
- `f-table-schema` : `slot="no-data"` support added to customize message when there are 0 rows.
=> issue-189 f-table-schema: no-data slot added to customise message 

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-date-time-picker/f-date-time-picker.ts, stories/flow-form-builder/f-formbuilder-field.ts
- `f-date-time-picker` : prevent the blur event from propagating when the date picker is open and date is selected. (It was validating value before input event in f-form-builder)
=> FLOW-964 f-date-picker blur event issue fixed

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-text/_f-text-variables-dynamic.scss, packages/flow-core/src/mixins/scss/_text-tokens.scss
- font-weights for `<f-text variant="heading"></f-text>` updated in text-tokens received from figma API.
=> FLOW-966 | Text Tokens font-weight bug, requires updation from figma

packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-trow/f-trow.ts
- `f-trow` : `chevron` reference added to trigger click externally using JS.
=> FLOW-967 chevron reference added in f-trow

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-input/f-input.ts
- re-exporting types of `f-input-base` from `f-input`. (To fix component type generation bug).
=> FLOW-971 f-input typescript issue fixed

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, packages/flow-core-config/CHANGELOG.md, packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.test.ts, packages/flow-core/src/components/f-breadcrumb/f-breadcrumb.ts, packages/flow-core/src/components/f-countdown/f-countdown-global.scss, packages/flow-core/src/components/f-countdown/f-countdown.scss, packages/flow-core/src/components/f-countdown/f-countdown.test.ts, packages/flow-core/src/components/f-countdown/f-countdown.ts, packages/flow-core/src/index.ts, stories/flow-core/f-breadcrumb.mdx, stories/flow-core/f-breadcrumb.stories.ts, stories/flow-core/f-countdown.mdx, stories/flow-core/f-countdown.stories.ts, stories/flow-core/f-pictogram.stories.ts
- `f-countdown`: component added in flow-core
=> FLOW-969 : f-countdown component

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-text/_f-text-variables-dynamic.scss, packages/flow-core/src/mixins/scss/_text-tokens.scss
- `f-text` : `x-large` tokens added for `para` and `code` variant.
=> FLOW-1084 - `f-text` : `x-large` tokens added for `para` and `code` variant.

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-div/f-div-global.scss, packages/flow-core/src/components/f-div/f-div.ts, packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table-schema/f-table-schema.ts, packages/flow-table/src/components/f-table/f-table-global.scss, stories/flow-core/f-div.stories.ts, stories/flow-table/f-table-schema.stories.ts, stories/utils/mock-users-data.ts
- `f-div` : Added `hide-scrollbar` property.
- (Note: The `hide-scrollbar` property will only hide the scrollbar; users can still scroll through the content.)
- `f-table-schema` : Added `sticky-cell-background` property.
- (Note: Any sticky element requires a background color; therefore, sometimes adjustments to this property may be needed when used with different surface backgrounds.)
=> FLOW-1119 hide-scrollbar property added to f-div

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-div/f-div-global.scss, packages/flow-core/src/components/f-div/f-div.ts, packages/flow-core/src/mixins/scss/_mixins.scss, stories/flow-core/f-div.stories.ts
- Added `show-scrollbar` property to `f-div`.
- Updated `f-div` to accommodate changes in Chrome v121, which now supports the `scrollbar-width` property. Default behavior adjusted accordingly.
- Removed `hide-scrollbar` property from `f-div`. Existing usage won't cause any issues.
=> FLOW-1162 scrollbar issue fixed in chrome v121

packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-tcell/f-tcell.ts, stories/utils/mock-users-data.ts
- `f-table-schema` : First cell content with checkbox is getting wrapped when content is large ot external template.
Before
After
=> FDS-644 f-table-schema first cell content is getting wrapped

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-select/f-select.test.ts, packages/flow-core/src/components/f-select/f-select.ts, packages/flow-core/src/components/f-select/render.ts, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-form-builder/src/components/f-form-builder/fields/select.ts, packages/flow-form-builder/src/types.ts, stories/flow-core/f-select.mdx, stories/flow-core/f-select.stories.ts
- The `f-select` virtualizer has been made optional and can be controlled using the `use-virtualizer` flag. This change will resolve the Cypress test case failure issue.
- The `useVirtualizer` property has been added to the `select` field to enable smooth search and selection for a large number of options.
=> FDS-651 The use-virtualizer option has been added to f-select to control its usage.

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/vite.config.ts
- We do need to consider how to lazily load the emoji mart code in future because this still doesn't fix the fact that the final client bundler will end up bundling everything together in the Flow bundle
- Same goes for other bigger libraries
=> Externalize lodash-es to reduce bundle size

packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-form-builder/src/components/f-form-array/f-form-array.ts, packages/flow-form-builder/src/components/f-form-builder/f-form-builder.ts, packages/flow-form-builder/src/components/f-form-builder/fields/text.ts, packages/flow-form-builder/src/components/f-form-object/f-form-object-global.scss, packages/flow-form-builder/src/components/f-form-object/f-form-object.ts, packages/flow-form-builder/src/modules/helpers.ts, stories/flow-form-builder/show-when-with-layout.stories.ts
- `showWhen` not working for `layout:'label-left'` fields.
- `layout:'label-left'` fields alignment fixed when used in object in horizontal direction.
=> FDS-654  showWhen not working for 'layout: "label-left" '  fields

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-counter/f-counter.ts, packages/flow-core/src/components/f-tag/f-tag.scss, packages/flow-core/src/components/f-tag/f-tag.ts, stories/flow-core/f-tag.stories.ts
- - Added `category` property to `f-tag` to support both `fill` and `outline` values. Default value set to `fill`.
=> FDS-661 category propetry added to f-tag

packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-form-builder/src/components/f-form-builder/fields/suggest.ts, packages/flow-form-builder/src/types.ts, stories/flow-form-builder/f-formbuilder-field.ts
- `optionsMaxHeight` property added for suggest field.
=> FDS-668 optionsMaxHeight added in suggest field of f-form-builder

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-select/f-select.ts, packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table-schema/f-table-schema.ts, stories/flow-table/f-table-schema.stories.ts
- `f-select` open on left side when rendered on extreme right of the window.
- Searchbar dropdown not opening.
=> FLOW-1795 FDS-669 f-select options opening side logic updated

packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table-schema/f-table-schema.ts
- Sorting issue for number column in `f-table-schema`
=> FDS-670 sorting issue with number column

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-select/f-select.scss, packages/flow-core/src/components/f-select/render.ts, packages/flow-core/src/components/f-tab-node/f-tab-node-global.scss, packages/flow-core/src/components/f-tab-node/f-tab-node.ts, packages/flow-table/CHANGELOG.md, packages/flow-table/package.json, packages/flow-table/src/components/f-table-schema/f-table-schema.ts, stories/flow-core/f-tab-node.mdx, stories/flow-core/f-tab-node.stories.ts
- `disabled` attribute added in `f-tab-node`.
- `f-select` chevron clikable area increased
- `f-table-schema` is not clearing the last selection when `selectable="single"`.
=> FDS-672 FDS-673 `f-table-schema` is not clearing the last selection when `selectable="single"`

packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-core/src/components/f-select/f-select.ts, packages/flow-core/src/components/f-select/handlers.ts, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-form-builder/src/components/f-form-builder/fields/select.ts, packages/flow-form-builder/src/modules/validation/validator.ts, stories/flow-form-builder/f-formbuilder-field.ts
- `f-select` outside click detection improved
- `select` with multiple selection empty array validation fixed
=> FLOW-1958 f-select bug fixes

.eslintrc.cjs, packages/custom-elements-manifest-to-types/CHANGELOG.md, packages/custom-elements-manifest-to-types/index.ts, packages/custom-elements-manifest-to-types/package.json, packages/flow-code-editor/CHANGELOG.md, packages/flow-code-editor/package.json, packages/flow-core/CHANGELOG.md, packages/flow-core/package.json, packages/flow-form-builder/CHANGELOG.md, packages/flow-form-builder/package.json, packages/flow-lineage/CHANGELOG.md, packages/flow-lineage/package.json, packages/flow-log/CHANGELOG.md, packages/flow-log/package.json, packages/flow-md-editor/CHANGELOG.md, packages/flow-md-editor/package.json, packages/flow-table/CHANGELOG.md, packages/flow-table/package.json
It works more reliably with their recommended way: https://vuejs.org/guide/extras/web-components#web-components-and-typescript
=> vue3-fix Fix Vue 3 type inference
